export const IPC_CHANNELS = {
  launchGame: 'game:launch',
  gameStatusChanged: 'game:status-changed',
  launcher: {
    selectInstallPath: 'launcher:select-install-path',
    getInstallPath: 'launcher:get-install-path',
    setInstallPath: 'launcher:set-install-path',
    getDirSummary: 'launcher:get-dir-summary',
    readLibraryDir: 'launcher:read-library-dir',
    openLibraryDir: 'launcher:open-library-dir',
    getSettings: 'launcher:get-settings',
    setSeriesOption: 'launcher:set-series-option',
    setGlobalOption: 'launcher:set-global-option',
    getAssetList: 'launcher:get-asset-list',
    downloadAsset: 'launcher:download-asset',
    cancelDownload: 'launcher:cancel-download',
    onDownloadProgress: 'launcher:on-download-progress',
  },
  mediaDownload: {
    start: 'media-download:start',
    cancel: 'media-download:cancel',
    progress: 'media-download:progress',
  },
  navigation: {
    openExternal: 'navigation:open-external',
  },
  series: {
    getStatus: 'series:get-status',
    install: 'series:install',
    launch: 'series:launch',
    verify: 'series:verify',
    remove: 'series:remove',
    revealInstallDir: 'series:reveal-install-dir',
    installProgress: 'series:install-progress',
    launchProgress: 'series:launch-progress',
  },
} as const;
